"""contractor-user

Revision ID: 1935315da710
Revises: b886a60ecea1
Create Date: 2024-04-20 19:25:24.623548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1935315da710'
down_revision: Union[str, None] = 'b886a60ecea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contractor', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.create_unique_constraint(None, 'user', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'contractor', type_='foreignkey')
    op.drop_column('contractor', 'user_id')
    # ### end Alembic commands ###
