"""date sales

Revision ID: 41496a08e91d
Revises: e060fe79e2dc
Create Date: 2024-04-21 04:30:59.087263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41496a08e91d'
down_revision: Union[str, None] = 'e060fe79e2dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('service_id', sa.Integer(), nullable=False))
    op.add_column('sales', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_constraint('sales_contractor_id_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'service', ['service_id'], ['id'], ondelete='cascade')
    op.drop_column('sales', 'contractor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('contractor_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_contractor_id_fkey', 'sales', 'contractor', ['contractor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sales', 'date')
    op.drop_column('sales', 'service_id')
    # ### end Alembic commands ###
