"""pasport-person

Revision ID: 819867d28bce
Revises: 9d7996af73f8
Create Date: 2024-04-20 22:23:39.155573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819867d28bce'
down_revision: Union[str, None] = '9d7996af73f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pasport', sa.Column('people_id', sa.Integer(), nullable=True))
    op.drop_constraint('pasport_series_key', 'pasport', type_='unique')
    op.create_foreign_key(None, 'pasport', 'people', ['people_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pasport', type_='foreignkey')
    op.create_unique_constraint('pasport_series_key', 'pasport', ['series'])
    op.drop_column('pasport', 'people_id')
    # ### end Alembic commands ###
