"""registration x,y

Revision ID: 8ec5d8f341b5
Revises: e35e401baf40
Create Date: 2024-04-20 23:12:14.179182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec5d8f341b5'
down_revision: Union[str, None] = 'e35e401baf40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration', sa.Column('x', sa.String(), nullable=True))
    op.add_column('registration', sa.Column('y', sa.String(), nullable=True))
    op.alter_column('registration', 'home',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('registration', 'flat',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registration', 'flat',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('registration', 'home',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('registration', 'y')
    op.drop_column('registration', 'x')
    # ### end Alembic commands ###
