"""pasport. unque serial and number

Revision ID: abb19f9b3a35
Revises: 58e077a15b86
Create Date: 2024-04-20 20:30:00.445473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abb19f9b3a35'
down_revision: Union[str, None] = '58e077a15b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pasport', ['number'])
    op.create_unique_constraint(None, 'pasport', ['series'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pasport', type_='unique')
    op.drop_constraint(None, 'pasport', type_='unique')
    # ### end Alembic commands ###
