"""init

Revision ID: b886a60ecea1
Revises: 
Create Date: 2024-04-20 01:59:14.256526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b886a60ecea1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('streat', sa.String(length=255), nullable=True),
    sa.Column('home', sa.Integer(), nullable=True),
    sa.Column('flat', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=255), nullable=False),
    sa.Column('pswd', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('balance_money', sa.Integer(), nullable=False),
    sa.Column('balance_bonus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pasport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series', sa.String(length=4), nullable=False),
    sa.Column('number', sa.String(length=6), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('date_issue', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['registration.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sec_name', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polis', sa.String(length=16), nullable=True),
    sa.Column('snils', sa.String(length=14), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.Column('pasport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pasport_id'], ['pasport.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benefit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['doc.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('benefit_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['benefit.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discount')
    op.drop_table('benefit')
    op.drop_table('doc')
    op.drop_table('people')
    op.drop_table('pasport')
    op.drop_table('user')
    op.drop_table('registration')
    op.drop_table('contractor')
    # ### end Alembic commands ###
