"""sales and service decimal

Revision ID: e060fe79e2dc
Revises: 614ecb7f0bde
Create Date: 2024-04-21 01:57:20.744074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e060fe79e2dc'
down_revision: Union[str, None] = '614ecb7f0bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'sum',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    op.alter_column('service', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'price',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('sales', 'sum',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
