"""contractor add photo

Revision ID: e35e401baf40
Revises: 819867d28bce
Create Date: 2024-04-20 22:25:18.555037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e35e401baf40'
down_revision: Union[str, None] = '819867d28bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractor', sa.Column('photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contractor', 'photo')
    # ### end Alembic commands ###
